# Generated by Django 5.2.7 on 2025-10-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionentry',
            name='allowed_finish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitionentry',
            name='time_remaining',
            field=models.PositiveIntegerField(blank=True, help_text='Time remaining in seconds', null=True),
        ),
    ]
