# Generated by Django 5.2.7 on 2025-10-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_competitionentry_allowed_finish_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitionentry',
            options={'verbose_name_plural': 'Competition entries'},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('entry', 'question')},
        ),
    ]
