# Generated by Django 5.2.7 on 2025-10-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_competitionentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='access_token',
            field=models.CharField(blank=True, help_text='If set, users must enter this token to attempt', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_questions',
            field=models.PositiveIntegerField(blank=True, help_text='Limit number of questions in an attempt', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='mode',
            field=models.CharField(choices=[('practice', 'Practice'), ('test', 'Test'), ('competition', 'Competition')], default='test', max_length=20),
        ),
    ]
