# Generated by Django 5.2.6 on 2025-11-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_reattemptrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='reattemptrequest',
            name='user_notified',
            field=models.BooleanField(default=False),
        ),
    ]
