# Generated by Django 5.2.6 on 2025-11-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_reattemptrequest_user_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='reattemptrequest',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
